First commit
wery0/GroebnerBasisLibrary pull request #1
Opened 2022-10-31 20:09 UTC by wery0

Черновой вариант реализации первых четырёх пунктов.

2022-11-12 20:27 UTC, DimaTrushin requested changes
Я сделал какие-то основные замечания по коду. Меньше всего смотрел на многочлены, уже не хватило сил. Как поправишь, я пробегусь еще раз. Там может и по старому коду появятся замечания.

2022-11-12 20:27 UTC, DimaTrushin commented on .gitignore
> +cmake-build-debug
В конце каждого файла делай пустую строку. Дело в том, что на отсутствие пустой строки ругается сам гит. А ты не хочешь, чтобы пользователь твоего кода видел ошибки от гита.

2022-11-12 20:27 UTC, DimaTrushin commented on CMakeLists.txt
> +
Добавь set(CMAKE_CXX_STANDARD_REQUIRED ON)
Потому что по умолчанию 4 строка не гарантирует 20 стандарт, а лишь попытается его использовать и если не получится откатится на более низкий стандарт.

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +    static_assert(std::is_integral_v<T>, "Number type must be an integral type");
Я бы еще добавил проерку, что T знаковый тип. Ты же не хочешь лишиться отрицательных чисел.

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +    T gcd(T x, T y) {
- А почему не используешь библиотечный gcd?
- Эта функция не привязана к конкретному объекту класса, потому она должна быть static

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +    T abs(T x) { return x < 0 ? -x : x; }
Эта функция должна быть static

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +        normalize();
Добавь сюда assert(denominator_); чтобы проверить корректность введенных данных. Вообще я рекомендую использовать assert везде, где только можно, чтобы отлавливать свои косяки.

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +        if (rhs.numerator_ == 0) { throw std::runtime_error("Fraction division by 0!"); }
Обычно при делении на ноль исключения не кидаются. Например встроенные типы не кидают такие исключения. Обычно деление на ноль -- это ошибка программиста, он забыл поставить проверку деления не на ноль. А раз это ошибка программиста, то ее надо исправить, а не кидать исключения. Потому тут лучше поставить assert(rhs.numerator_); и программа упадет в дебаге при делении на ноль и ты исправишь эту ошибку.

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +    void operator+=(const Fraction& rhs) {
- Во-первых, не правильная сигнатура оператора. Она должна быть
```cpp
Fraction& operator+=(const Fraction& rhs)
```
- Во-вторых, обычно операторы имплементируют наоборот в следующем смысле. У тебя есть inplace операторы такие как +=, -=, *=, /= они оперируют над объектом this непосредственно. И есть генерирующие новый объект операторы вроде +, -, *, /. Так вот inplace операторы обычно можно сделать более эффективными и потому сначала реализуют inplace версии, а потом с помощью них реализуют бинарные. Например
```cpp
Fraction& operator*=(const Fraction& rhs) {
  numerator_ *= rhs.numerator_;
  denominator_ *= rhs.denominator_;
  normalize();
  return *this;
}
friend Fraction operator*(const Fraction& lhs, const Fraction& rhs) {
  Fraction result = lhs;
  result *= rhs;
  return result;
}
```
В этом случае автоматически затригерется rvo и временный объект не будет конструироваться.
Кроме того, бинарные операторы лучше делать friend-ами, тогда они допускают конверсию по двум аргументам. А именно, у тебя конструктор из типа T не является explicit, потому в выражении x + y; если y типа Fraction<T>, а x типа T, то компилятор преобразует x к Fraction<T> и потом вызовет оператор для Fraction<T>.

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +    Fraction operator+(const Fraction& rhs) const {
Бинарные операторы лучше делать в виде friend операторов (смотри ниже комментарий к оператору +=)
```cpp
friend Fraction operator+(const Fraction& lhs, const Fraction& rhs) {...}
```
И их лучше реализовывать через inplace версии операторов.

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +    bool operator!=(const Fraction& rhs) const { return ((*this) - rhs).numerator_ != 0; }
Более грамотно будет реализовать новый оператор через уже написанные, например тут стоит написать (и лучше сделать friend версию)
```cpp
friend bool operator!=(const Fraction& lhs, const Fraction& rhs) {
  return !(lhs == rhs);
}
```
Так как у тебя все внутри шаблона, компилятор непостесняется заинлайнить весь код.

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +    bool operator>(const Fraction& rhs) const { return ((*this) - rhs).numerator_ > 0; }
Этот оператор можно выразить через предыдущий. Кроме того, можно еще добавить нестрогие операторы <= и >=

2022-11-12 20:27 UTC, DimaTrushin commented on Fraction.h
> +    friend Fraction inv(const Fraction& f) { return {f.den, f.num}; }
По сути эта функция и функция на строке 68 делают одно и то же. Непонятно зачем тебе задвоенный функционал. А вот чего не хватает -- метода обращения Inplace. По хорошему лучше сделать так добавить метод invert, который обращает this. А потом с помощью него реализовать static метод invert(const Fraction& rhs). Тогда первый будет вызываться f.invert() и ты обращаешь сам f. А второу будет вызываться invert(f) и ты строишь новый объект.

2022-11-12 20:27 UTC, DimaTrushin commented on Mint.h
> +    static_assert(std::is_integral_v<T>, "Number type must be an integral type");
Не хочешь ли ты добавить, что T должен быть знаковым, чтобы не было проблем с -1 и его конвертацией к остаткам?

2022-11-12 20:27 UTC, DimaTrushin commented on Mint.h
> +
Все замечания по операторам, которые были для рациональных, релевантны и тут.

2022-11-12 20:27 UTC, DimaTrushin commented on Mint.h
> +    Mint(U c) {
Это опциональное замечание. Если хочешь инициализировать val_ в списке инициализации, то обычно в этом случае вводят функцию reduce (статическу и приватную) и потом пишут Mint(U c) : val_(reduce(c)) {} И уже функция reduce выполняет всю нормализацию значения.

2022-11-12 20:27 UTC, DimaTrushin commented on Mint.h
> +    T val_ = 0;
не сокращай слова до трех букв, value_ ни чуть не хуже

2022-11-12 20:27 UTC, DimaTrushin commented on Mint.h
> +        for (T x = val_; pw; pw >>= 1) {
Вот это мне не нравится. Битовые сдвиги на знаковых типах -- опасная штука.
For negative a, the value of a >> b is implementation-defined (in most implementations, this performs arithmetic right shift, so that the result remains negative).
Что если pw < 0?

2022-11-12 20:27 UTC, DimaTrushin commented on Mint.h
> +    Mint get_inv(const Mint& m) const { return get_pow(MOD - 2); }
Ты никак не используешь аргумент, вместо этого ты оперируешь над this.

2022-11-12 20:27 UTC, DimaTrushin commented on Mint.h
> +    friend Mint inv(const Mint& m) { return m.get_pow(MOD - 2); }
Опять задвоенный функционал.

2022-11-12 20:27 UTC, DimaTrushin commented on Variable.h
> +    NumberType number_ = -1;
чтобы подчеркнуть, что -1 -- особое значени, означающее, что нет индекса, можно ввести специальную константу
```cpp
static constexpr NumberType kNoIndex = -1;
...
NumberType number_ = kNoIndex;
```

2022-11-12 20:27 UTC, DimaTrushin commented on Variable.h
> +    bool operator<(const Variable& rhs) const {
Так как у тебя в будущем будет использоваться абсолютно разный порядок на переменных, то вшивать сюда какой-то порядок как канонический -- плохая идея. Лучше уж тогда реализоваться классы сравнения переменных и скармливать их различным контейнерам вроде map.

2022-11-12 20:27 UTC, DimaTrushin commented on Variable.h
> +        if (!isalpha(letter)) {
isalpha зависит от текущей locale. Что может дать плохой результат у этой функции, когда кто-то поставит не английский язык.

2022-11-12 20:27 UTC, DimaTrushin commented on Variable.h
> +            throw std::runtime_error(err_msg);
Я не уверен, что тут хорошая идея кидать exception. Скорее всего assert будет более приемлемой альтернативой.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +        if (s.empty()) { return; }
Слишкмо большая функция. Тут проблема с несоблюдением уровня абстракции. У тебя совершается слишком низкоуровневая работа тут. По хорошему код должен быть типа такого
```cpp
explicit Monomial(const std::string& s) {
  MonomialParser p;
  auto result = p.parse(s);
  if(!result.has_value())
    throw std::runtime_exception("");
  ...
}
```
То есть вся возня с разбором строки должна быть зашита в отдельный объект, чтобы не скрывать глобальную логику конструирования объекта.

Так же, если парсер может бросать исключения, их стоит завернуть в try catch блоки. И я не уверен, что исключения -- это хорошая идея тут.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +    Monomial(const CoefficientType& coefficient, const std::map<Variable<VariableNumberType>, DegreeType>& var_store)
- Инициализировать с помощью std::map -- не самая лучшая идея. Тебе надо построить этот map вне монома, а потом ты из него всю информацию копируешь. Как минимум сделать rvalue reference и потом move из нее было бы более правильно. Кроме того, на такой счет предусмотрен std::initializer_list. Я просто пытаюсь представить, как ты будешь использовать этот конструктор. Наверное что-то вроде Monomial m(2.0, {{'x', 2}, {'y', 3} }); Если так, то initializer_list более предпочтительный.
- Кроме того, у тебя DegreeType знаковый тип. Потенциально в std::map могут лежать отрицательные степени, что делает твои мономы некорректными. Это надо проверять в теле конструктора. Вообще задача конструктора следить за всеми инвариантами класса, чтобы он был построен корректно.
- Так же надо проверить, что нет нулевых степеней, точнее удалить все переменные в нулевых степенях, чтобы их не хранить.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +    Monomial operator*(const Monomial& rhs) const {
Замечания про операторы те же, что и для Fraction.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +    bool operator==(const Monomial& rhs) const {
Вот это очень плохо. Пользователь библиотеки будет обманут этим оператором. Кроме того, когда коэффициент нулевой, то тебе должно быть плевать какой моном. Вообщем тут много вопросов к этой функции.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +        for (; it1 != var_store_.end(); ++it1, ++it2) {
Почему так сложно? Почему нельзя написать var_store_ == rhs.var_store_?

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +    bool empty() const { return var_store_.empty(); }
Плохое название функции. Для монома не имеет смысла функци empty. Потому что что такое пустой моном? Эта функция взялась как деталь имлементации. Надо вырезать ее и ее использования.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +        if (rhs.coefficient_ == 0) { throw std::runtime_error("Division on zero monomial"); }
Ты тут страдаешь из-за того, что у тебя по сути есть две сущности: коэффицент и моном (который только от переменных). И операции которые ты пытаешься тут ввести они верны только для монома (который только от переменных), а ты пытаешься их сделать для пары (коэффициент, моном). Это ошибка дизайна. По хорошему надо разделить их.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +        for (const auto& [var, deg] : rhs.var_store_) {
Обычно такие циклы можно упростить следующим образом. Тебе нужна функция degree_of_variable(const Variable& v); которая отрабатывает для любой переменной даже той, которой нет в мономе (тут она дает 0). А потом уже можешь пробежаться по переменным делителя и проверить, что степени по этим переменным у делимого не меньше.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +    friend DegreeType degree(const Monomial& monomial) { return monomial.get_degree(); }
опять задвоенная функция.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +    mutable CoefficientType coefficient_;
Какого хрена у тебя коэффициент mutable? То есть ты можешь в константном мономе поменять коэффициент! Это косяк дизайна. Надо точно убрать и исправить.

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +template<typename CoefficientType, typename Order = MonomialOrders::Grlex, typename DegreeType = int64_t,
Основная проблема с этим классом в том, что ты пытаешься объеденить в одно две разные вещи. По хорошему этот класс у тебя представляет пару (коэффициент, моном), где моном только от переменных. И у тебя часть операций верны только для монома (который только от переменных) из-за этого ты вводишь противоестественные операции.

2022-11-12 20:27 UTC, DimaTrushin commented on MonomialOrder.h
> +
Как я вижу порядок на переменных у тебя получается постоянным. Наверное так можно для начала оставить.

2022-11-12 20:27 UTC, DimaTrushin commented on MonomialOrder.h
> +            return std::lexicographical_compare(m2.var_store_.begin(), m2.var_store_.end(),
- Если я правильно понимаю, то begin в map начинает с элемента с наименьшим ключем. То есть ты смотрешь от младшей переменной к старшей.
- Как у тебя будут сравниваться мономы 'xz' и 'y'. У тебя в начале сравнятся переменные 'x' и 'y'. и 'y' окажется старше. Что противоречит тому, что должно быть. Я к тому, что это похоже на неверную имплементацию порядка.

2022-11-12 20:27 UTC, DimaTrushin commented on MonomialOrder.h
> +    struct Grlex {
Вообще хотелось бы не хардкодить порядки а собирать их из других порядков. Например хотелось бы иметь порядок Lex и порядок Deg, а потом уметь собрать DegLex = Sum<Deg, Lex>; или что-то в этом духе.

2022-11-12 20:27 UTC, DimaTrushin commented on MonomialOrder.h
> +            return std::lexicographical_compare(m2.var_store_.begin(), m2.var_store_.end(),
Корректность тут я бы тоже проверил. И еще, если это DegLex, то вместо std::lexicographical_compare было бы правильнее использовать сравнение из Lex()

2022-11-12 20:27 UTC, DimaTrushin commented on MonomialOrder.h
> +            return std::lexicographical_compare(m1.var_store_.rbegin(), m1.var_store_.rend(),
Тоже подумать над корректностью.

2022-11-12 20:27 UTC, DimaTrushin commented on Polynomial.h
> +        if (m.coefficient_ != 0) { monom_store_.insert(m); }
- Зачем тебе делать Polynomial другом, если у тебя есть метод get_coefficient()?
- Если уж ты передал моном by value, то сделай move, а именно insert(std::move(m));

2022-11-12 20:27 UTC, DimaTrushin commented on Polynomial.h
> +    bool empty() const { return monom_store_.empty(); }
плохой метод. Его не должно быть в интерфейсе полинома.

2022-11-12 20:27 UTC, DimaTrushin commented on Polynomial.h
> +    explicit Polynomial(const std::set<Monom>& store) : monom_store_(store) {}
Если уж и делаешь конструктор из set, то лучше из rvalue reference и делать move.

2022-11-12 20:27 UTC, DimaTrushin commented on Polynomial.h
> +            (*monom_store_.find(m)).coefficient_ += m.coefficient_;
Вот это то место, где тебе нужен mutable коэффициент. Проблему можно решить двумя способами.
1) Ты делаешь extract нода из set-а, модифицируешь нод и потом добавляешь его обратно.
https://en.cppreference.com/w/cpp/container/set/extract
2) Ты делаешь моном без коэффициентов, а тут хранишь map<coefficient, Monom>.

2022-11-12 20:27 UTC, DimaTrushin commented on Polynomial.h
> +        std::vector<Monom> zero_monoms;
Это какой-то мега кривой способ удалять элементы из set-а. Вместо этого сделай цикл от begin к end, точнее
```cpp
auto it = monom_store_.begin();
while(it != monom_store_.end()) {
  if(it->isZero())
    it = monom_store_.erase(it);
  else
    ++it;
}
```

2022-11-12 20:27 UTC, DimaTrushin commented on Monomial.h
> +    friend class Polynomial;
Вот эти два friend-а -- это сто процентов ошибка проектирования.

2023-02-20 12:04 UTC, DimaTrushin requested changes
В целом неплохо. Стало сильно лучше. Нашел один баг при умножении многочленов и еще кучу мелких замечаний по производительности и по качеству кода.

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +        assert(rhs.denominator_ && "Fraction can't have a zero denominator");
Если уж ты проверяешь preconditions для функции, то проверяй все. У тебя еще может нарушиться условие denominator_ != 0 для this.

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
>      bool operator==(const Fraction& rhs) const { return ((*this) - rhs).numerator_ == 0; }
Если у тебя дроби всегда нормализованы, то достаточно проверить, что числители и знаменатели совпадают. Но можно и так оставить.

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +    friend bool operator!=(const Fraction& lhs, const Fraction& rhs) { return !(lhs == rhs); }
Перенеси этот оператор выше, сразу после оператора равенства. Потому что они относятся к друг другу.

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +    friend bool operator<=(const Fraction& lhs, const Fraction& rhs) { return lhs < rhs || lhs == rhs; }
Можно проще: return !(rhs < lhs);

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +    void pow(T power) { binpow(numerator_, denominator_, power); }
Мне всегда казалось плохой идеей передавать по неконстантной ссылке переменные. Тут надо догадываться, что числитель и знаменатель меняются. И не понятно, почему не сделать эти действия над this напрямую.

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +        return os << std::string("\\frac{") << f.numerator_ << "}{" << f.denominator_ << "}";
Ооо, прям в LaTeX.

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +        normalize();
По идее, эта функция не понадобится, если дроб изначально была нормализована. То есть можно нормализацию проверить ассертом (кстати, это тоже прекондишн для всех твоих функций).

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +    static int sign(T x) { return x < 0 ? -1 : x == 0 ? 0 : 1; }
А почему знак не типа T?

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +        T sign = numerator > 0 ? 1 : -1;
Почему не пользуешься функцией знака? Чисто оптимизация?

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +        assert(pow >= 0 && "Negative power is not allowed!");
Сразу замечание к момему комментарию. Можно оставить как есть. Сейчас это все работает. Просто поделился мыслями ниже.

Я так понимаю, этой проверкой ты избавляешься от implementation defined поведения в операторе pow >>= 1. Сдвиги всегда не безопасные операции. Я бы рекомендовал использовать pow /= 2. Потому что это всегда работает, это корректно определено для любого pow. И по производительности нет никакой разницы с pow >>= 1. Разница появляется, если у тебя pow >>= b и b не известно в момент компиляции. Во всех остальных случаях /= предпочтительнее из-за безопасности.

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
> +        T gc = std::__gcd(abs(numerator_), denominator_);
А почему не std::gcd??? Имена с __ в начале обычно являются деталями имплементации в stl.

2023-02-20 12:04 UTC, DimaTrushin commented on Fraction.h
>          denominator_ /= gc;
Если ты сохраняешь числитель и знаменатель взаимно простыми. То стоит это условие тоже проверять в виде прекондишн, если ты его проверяешь в начале методов класса. Для удобства можно выделить функцию check_class_invariant или что-то в этом духе. Но я думаю, что можно перестать возиться с этим классом.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +    static_assert(is_polynomial<Polynom>::value);
можно сделать статическую константу
```cpp
template<typename P>
constexpr bool is_polynomial_v = is_polynomial<P>::value;
```
и потом просто проверять is_polynomial_v<Polynom>

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +        for (auto& p : store) { insert(p); }
Так как у тебя константный вектор, то и p будет константного типа. так что const auto& будет более наглядно.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +    Ideal(const std::vector<Polynom>& store) {
Не хочешь добавить поглощающий конструктор вида Ideal(std::vector<Polynom>&& store) ? для того, чтобы сделать move в Ideal всех многочленов, а не копировать их, когда в этом есть необходимость?

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +    Ideal(const std::vector<Polynom>& store) {
В целом идея конструктора от конкретного контейнера -- не всегда хороша. Потому что если ты сделаешь что-то вроде
```cpp
Ideal MyIdeal = {f1, f2, f3}; // пусть fi -- это какие-то выражения задающие многочлены.
```
То у тебя будет создан std::initializer_list<Polynom> и потом этот initializer_list инициализирует std::vector<Polynom>. Тут будет O(n) move операций на многочленах. После чего, так как вектор у тебя константный, у тебя произойдет O(n) операций insert и при каждом insert временный полином в векторе будет полностью скопирован. Потому это будет дорогостоящей операцией. И так будет при каждой инициализации идеала списком. Потому предпочтительнее делать std::initializer_list, а для конкретных конструкторов (например от вектора) делать поглощающий конструктор.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +    void insert(const Polynom& p) {
Стоит добавить поглощающую версию void insert(Polynom&& p)

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +    void reduce(Polynom& rhs) const {
Плохая идея передавать изменяемый объект по неконстантной ссылке. Лучше уж передавать его по указателю, чтобы пользователь видел, что ты меняешь объект.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +        for (;;) {
такой for ничуть не лучше while(true). Я бы сделал так
```cpp
bool was_reduced = false;
do {
  was_reduced = reduce_by_set_once(rhs);
} while(was_reduced);
```
и уже в функции reduce_by_set_once сделал бы цикл по всем элементам множества.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +    bool is_redusable_to_zero(Polynom rhs) const {
Вот это кстати неплохо.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +                if (gcd(store_[i].get_highest_monomial(), store_[j].get_highest_monomial()).get_variables().empty()) {
Вместо этой паршивой проверки, сделай функцию are_leading_monomials_coprime(store_[i], store_[j]) и будет сильно лучше читаться.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +                insert(p);
Вот тут тебе точно нужна поглощающая версия insert с вызовом insert(std::move(p));

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +                reduce(p);
вот тут будет лучше читаться если написать reduce(&p) и будет понятно, что p редуцируется.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +        for (int i = 0; i < store_.size(); ++i) {
Любопытно организовано, я даже не сразу понял, что это верно работает. Мне интересно понять, на сколько реаллокация вектора тут может покоцать производительность. Если что-то такое же сделать с std::list и перед алгоритмом в него все скопировать и пользоваться итераторами вместо индексов. Будет ли это заметно быстрее? Это так мысли вслух. Их можно сейчас игнорировать.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +                if (store_[q].get_highest_monomial().is_divisible_on(store_[w].get_highest_monomial())) {
сделай нормальную вспомогательную функцию для условия.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +                    store_.erase(store_.begin() + q);
Это потенциально дорогая операция на векторе. Куда лучше было бы сделать swap текущего элемента и последнего и потом удалить последний элемент. Надо быть еще аккуратным, чтобы не убить алгоритм этими действиями, потому что у тебя два индекса.
Может быть правильное решение составить новый вектор из редуцированного базиса и потом сделать move.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +            other.erase(other.begin() + q);
Это жутко дорогая операция в цикле.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +            Ideal<Polynom> i(other);
- А вот и приплыли, ты не можешь применить алгоритм не создав идеал. У тебя алгоритм не работает со стандартными контенерами. А вот была бы версия алгоритма для любого контейнера, то можно было бы скопировать все полиномы в std::set. Потом из него легко удалять и добавлять один элемент. И потом легко было бы редуцировать по контейнеру.
- Ну и название i -- это просто плевок в сторону читателя кода.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +            std::vector<Polynom> other = store_;
Супер дорогая операция в цикле. Почему не сделать копию до цикла и потом делать локальные манипуляции с копией?

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +        for (int q = 0; q < store_.size(); q++) {
Нарушение уровня абстракции. У тебя в строке 63 идет вызов функции, а тут идет пара сырых лупов. То есть строка 63 идет на более высоком уровне абстракции, чем строки после нее. То есть я бы ожидал 
```cpp
make_groebner_basis();
exclude_unnecessary_polynomials();
```

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +        for (int q = 0; q < store_.size(); q++) {
Нарушение уровня абстракции.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +        for (int q = 0; q < store_.size(); q++) {
почему не ++q?

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +        for (const auto& p : store_) { assert(p.get_highest_monomial().get_coefficient() == 1); }
Это должно быть assert(are_all_polynomials_with_leading_coefficient_one());
Потому что иначе в проде у тебя тут лишний пустой луп. Можно надеяться, что компилятор оптимизирует и выкинет пустой луп (так скорее всего и будет), но для читателя кода не понятно, что это проверка инварианта. Название, кстати, надо еще продумать, слишком длинное.

2023-02-20 12:04 UTC, DimaTrushin commented on Ideal.h
> +    Polynom get_S_polynomial(const Polynom& p1, const Polynom& p2) {
1) Этот метод должен быть static, так как не зависит от самого множества.
2) Этот метод должен быть публичным, потому что мы можем захотеть построить S-полином по заданным полиномам.
3) Из пункта (2) вытекает, что если у тебя есть два многочлена, то чтобы построить их полином, тебе нужен доступ к идеалу, что не логично. Это говорит об ошибке проектирования, про которую я уже писал. Эту ошибку с STL допустили при проектировании std::string. std::string содержит кучу методов, которые работают только для string, но имеют смысл для любого контейнера и пользователям приходится эти методы писать заного вручную. Это печаль, беда и огорчение.

2023-02-20 12:04 UTC, DimaTrushin commented on Mint.h
> +        static_assert(std::is_integral_v<T> && std::is_signed_v<T>, "Numeric type must be signed and integral");
Тут наверное U вместо T

2023-02-20 12:04 UTC, DimaTrushin commented on Mint.h
>  };
новая строка.

2023-02-20 12:04 UTC, DimaTrushin commented on Mint.h
> +        value_ -= value_ < MOD ? 0 : MOD;
Почему просто не написать value_ %= MOD;? Или это оптимизация? Если оптимизация, то не понятно, что быстрее сработает if, который может ошибиться с предсказанием перехода на ядре или детерменированное деление с остатком. Я бы делал ставку, что %= будет быстрее. Ты это тестировал? Ну и конечно %= будет тупо понятнее при чтении кода.

2023-02-20 12:04 UTC, DimaTrushin commented on Mint.h
> +        value_ *= binpow(rhs.value_, MOD - 2);
- Если у тебя есть inverse, то почему тут не воспользоваться им, например *this *= rhs.invert()? Это будет в одну строчку. Или это выглядит как оптимизация?
- Еще хотел спросить. Всегда было интересно, что работает быстрее расширенный алгоритм евклида или возведение в степень. Можешь проверить производительность?

2023-02-20 12:04 UTC, DimaTrushin commented on Mint.h
> +    friend bool operator!=(const Mint& lhs, const Mint& rhs) { return !(lhs == rhs); }
перенеси оператор неравенства выше к оператору равенства.

2023-02-20 12:04 UTC, DimaTrushin commented on Mint.h
> +    friend bool operator<=(const Mint& lhs, const Mint& rhs) { return lhs < rhs || lhs == rhs; }
то же замечание, что и в операторах для рациональных дробей.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +template<typename CoefficientType, typename VariableOrder = VariableOrders::AsciiOrder, typename DegreeType = int64_t,
Меня смущяет, что DegreeType знаковый. У тебя степень может быть отрицательная? Или это просто для удобства работы со степенями? Ассерты на неотрицательность не забываешь везде проставить?

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +        parser.parse(s, coefficient_, var_store_);
Опять же та же самая логика с in и out параметрами. in параметры передаем by value или by const reference, а out параметры передаем by pointer. in параметры идут перед out параметрами.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +    Monomial(CoefficientType coef, Var var, DegreeType deg) : coefficient_(coef) {
- У тебя CoefficientType всегда легкий? Если нет, то лучше сделать coefficient_(std::move(coeff)).
- Ну и ты все время сокращаешь. Сейчас уже лучше, чем было. Но ты не постоянен в выборе обозначений. Например тут coefficient_ но при этом coef.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +        if (coef != 0 && deg != 0) { var_store_[var] = deg; }
добавсь deg >= 0 вместо deg != 0. Потому что код должен работать и с ассертами и без. То есть мы вряд ли хотим, чтобы программа не работала при негативной степени. Пусть просто создается тривиальный моном.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +        coefficient_ *= rhs.coefficient_;
Этот метод работает неправильно, если rhs имеет нулевой коэффициент. Я подразумеваю инвариант, что в случае нулевого коэффициента var_store_ должен быть пуст.
Можно было бы использовать метод из строчки 46, например *this *= rhs.coefficient_;

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +            if (!var_store_.count(var)) var_store_[var] = 0;
Вот эта строчка должна быть лишней, потому что для std::map оператор operator[] при вызове var_store_[var] добавляет пару {var, Value()}. А для всех встроенных типов Value() будет нулем. Потому строчки 36 достаточно.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +        coefficient_ /= rhs.coefficient_;
assert на нулевой коэффициент не хочешь?

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +        if (rhs.coefficient_ == 0) { return false; }
Опять похоже на лажу. Что если coefficient_ равен нулю? Тогда должно делиться на любой rhs (даже включая ненулевой?). Но тогда цикл ниже не работает в случае нулевого this.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +    void increase_coefficient(const CoefficientType& coefficient) { coefficient_ += coefficient; }
coefficient больше похоже на offset или что-то в этом духе.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +    const std::map<Var, DegreeType>& get_variables() const { return var_store_; }
- Ты уверен, что ты хочешь раскрывать детали имплементации? Где тебе это может понадобиться? Это делает класс хрупким, ты по сути ломаешь инкапсюляцию. Каждый раз, когда ты будешь менять имплементацию класса, все пользователи ломают свой код в этом месте. Это гипотетическая проблема, но она показывает, что ты скорее всего плохо продумал границы взаимодействия класса с другими объектами.
- Я увидел, как ты это используешь для сравнения мономов. Тут можно вернуть прокси объект, у которого есть свои begin и end и итераторы, чтобы бежать по переменным в определенном порядке. И сделать два метода: Proxy get_variables_accending_order(), Proxy get_variables_deccending_order()

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +        const auto& vars = m2.get_variables();
Ну вот и всплыло место, где надо иметь отдельный объект для мономов без коэффициента.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +    }
А у тебя выполняется инвариант m1 * m2 = gcd(m1, m2) * lcm(m1, m2)? Я просто не уверен, да и устал немного копаться в корнеркейсах. Собственно почему не определить lcm = m1 * m2 / gcd?

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
>          if (coef < 0) {
Вот это тонкое место. Но в общем случае мы с ним не поборемся. Хочу просто обратить внимание, что если коэффициенты могут быть любые, то ты начинаешь требовать для них порядка и этот порядок равносилен наличию знака перед коэффициентом. Но это все может не имметь смысла для каких-то полей. Хорошего решения у меня сейчас нет. Пусть будет так.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +            auto& [var, deg] = *it;
почему не const auto&?

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +    struct MonomialParser {
Я бы вынес парсер в отдельный h файл, чтобы не захломлять имплементацию монома.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +        void parse(const std::string& s, CoefficientType& coefficient, std::map<Var, DegreeType>& var_store) {
Тут у тебя нарушение ответственности. Парсер делает сразу две вещи он парсит и коэффициенты и переменные. Это сложно исправить при таком дизайне.

2023-02-20 12:04 UTC, DimaTrushin commented on Monomial.h
> +            if (s.empty()) { return; }
Функция слишком длинная. Нужен рефакторинг. Но я сейчас это читать не буду ибо помру. По-хорошему у тебя должен быть парсер коэффицентов. Например в виде шаблона CoefficientParser<CoefficientType> p;
И ты делаешь его специализацию для всех видов коэффициентов, которые тебе нужны (и эта штука ругнется на неподдерживаемый тип). И потом делаешь coefficient_ = p.parse(s);
А потом делаешь  VariableParser p; var_store_ = p.parse(s); и все.

2023-02-20 12:04 UTC, DimaTrushin commented on MonomialOrders.h
> +
Это вроде похоже на правду, но я внимательно не всматривался.

2023-02-20 12:04 UTC, DimaTrushin commented on MonomialOrders.h
> +            static Lex l;
static -- хитро.

2023-02-20 12:04 UTC, DimaTrushin commented on MonomialOrders.h
> +            if (v1 == v2) { return false; }
Я думаю, что revlex можно тоже определить через std::lexicographical_compare со специальной функцией сравнения пар. Это позволит избавиться от явного цикла.

2023-02-20 12:04 UTC, DimaTrushin commented on MonomialOrdersTest.cpp
> +
Все что пишется в global namespace в cpp файлах кроме main должно быть перемещено в anonymous namespace.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +    using Polynom = Polynomial<Monom, MonomialOrder>;
Зачем этот using? Внутри шаблона имя шаблона можно исопльзовать без аргументов. Например, везде где тебе нужен Polynomial<Monom, MonomialOrder> ты можешь просто писать Polynomial.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +    Polynomial(const Monom& m) {
Нужен поглощающий конструктор с Monom&& и мувом в insert.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
>      Polynomial(std::string s) {
Опять выглядит, как необходимость сделать парсер и вызвать его тут.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +    Polynomial& operator*=(const auto& rhs) {
- А почему тут auto? Это чтобы не писать отдельно для коэффициента и для монома?
- Увидел следующий оператор на 86 и первая мысль: скажу спокойно я не психуя, какого хера, какого хуя? Почему тогда тут auto, а не CoefficietyType?

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +        remove_zero_monomials();
Быстрее будет в начале проверить rhs.is_zero() или нет.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +    Polynomial& operator*=(const Monom& rhs) {
Это выглядит как повторение предыдущих трех операторов. Чего я не вижу?

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +            for (const auto& monom2 : rhs.monom_store_) { new_store.insert(monom1 * monom2); }
Вот это должн оработать не верно. Ибо set, если видит эквивалентный элемент, то не добавляет новый, а оставляет старый нетронутым. А у тебя может получиться что ты перемножаешь *this = x^2y + xy^2 и rhs = x + y. Тогда там моном x^2 y^2 встретится дважды как x^2y * y и как xy^2 * x. И тогда один из них у тебя не учтется судя по всему. Ты не учитываешь приведение подобных слагаемых никак. Это проблема. В прошлой версии кода, у тебя вызывался оператор add, который это учитывал. Тут можно это поправить так же, сделав оператор add. Либо ты можешь создать Polynomial res вместо множества мономов и просто прибавлять к нему произведение мономов в цикле. А потом сделать *this = std::move(res); Либо более аккуратно почленный move, так как если Coefficients по каким-то причинам не поддерживает move, то тут может вызваться копирование.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +    Polynomial& operator/=(const auto& rhs) { return (*this) *= invert(rhs); }
Почему auto? На что ты в принципе можешь делить многочлен кроме коэффициента или монома? И еще очень странно, что при этом invert у тебя метод полиномов! Потому что auto может быть кто угодно, то почему класс полиномов должен уметь это auto обращать?

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +    Polynomial& operator/=(const Monom& rhs) {
Это не безопасный метод в том смысле, что он может не сработать. Хорошо бы добавить метод проверки делимости полинома на моном. Потому что иначе у пользователя этого метода нет возможности проверить, может ли он вызывать этот метод безопасно.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +        remove_zero_monomials();
По идее не понятно, зачем этот метод тут. Вроде ничего занулиться не может при таком делении.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +    bool operator==(const Polynomial& rhs) const { return monom_store_ == rhs.monom_store_; }
- Я может быть проглядел, но я не увидел у мономов оператор сравнения на равенство. Потому я не понимаю, как оператор сравнения std::map может сработать. Он же должен поэлементно сравнить мономы, а этого оператора нет. Или я не увидел его?
- Кроме того, почему тут не friend? Ты хочешь запретить конвертацию к многочленам по первому аргументу?

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +        return Monom();
Было бы круто иметь static функцию 
static Monomial ZeroMonomial();
внутри класса мономов, чтобы тут написать Monom::ZeroMonomial() и точно быть уверенным, что это нулевой моном.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +    Monom get_highest_monomial() const { return *monom_store_.rbegin(); }
- Что если полином нулевой?
- У этой функции и у следующей разная политика при отсутствии ответа. Эта функция падает, а следующая возвращает нулевой моном. Надо определиться чего ты хочешь и сделать один и тот же подход.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
>      void add(const Monom& m) {
Ну вот у тебя есть нужная функция для произвденеия operator*. Надо ее только использовать вместо insert.

2023-02-20 12:04 UTC, DimaTrushin commented on Polynomial.h
> +        if ((*monom_store_.find(m)).get_coefficient() == 0) { monom_store_.erase(m); }
Нулевым может стать только тот момном, который ты только что вставил. Потому достаточно для nh сделать проверку, что его коэффициент не ноль и после этого вставить его обратно.

2023-02-20 12:04 UTC, DimaTrushin commented on Variable.h
>          if (v.number_ == -1) { return os << v.letter_; }
Используй константу kNoIndex вместо -1.

2023-02-20 12:04 UTC, DimaTrushin commented on main.cpp
> +}
строка =)

2023-05-16 18:06 UTC, wery0 commented on Fraction.h
> +    static int sign(T x) { return x < 0 ? -1 : x == 0 ? 0 : 1; }
Знак используется только в одной функции, где знаки либо сравниваются между собой, либо сравниваются с интами. Так что кажется нет смысла лишний раз кастовать к типу T.

2023-05-16 18:06 UTC, wery0 commented on Fraction.h
> +        T sign = numerator > 0 ? 1 : -1;
Ага.

2023-05-16 19:50 UTC, wery0 commented on Mint.h
> +        value_ -= value_ < MOD ? 0 : MOD;
Потестировал и получил такие результаты:
Без -O2 оптимизации: 
  Если MOD известен во время компиляции: данный способ медленнее %= в ~3 раза.
  Если MOD неизвестен во время компиляции: данный способ медленнее %= в ~2 раза.

С -O2 оптимизацией:
  Если MOD известен во время компиляции: данный способ быстрее %= в 2-3 раза (в этом случае время работы %= зависит от самого MOD кстати).
  Если MOD неизвестен во время компиляции: данный способ быстрее %= в 8-10 раз.

Ну и добавлю, что именно таким способом реализуется сложение и вычитание в известных мне быстрых реализациях модульной арифметики.
А ещё, если мы хотим делать много умножений/делений по модулю, то работу программы могут ускорить умножение Монтгомери, а также алгоритм Барретта, но это уже совсем другая история...

2023-05-16 21:31 UTC, wery0 commented on Mint.h
> +        value_ *= binpow(rhs.value_, MOD - 2);
1). Да, это оптимизация.
2). При тестировании использовал MOD = 915068459 (случайное простое число), в общем случае время работы пропорционально величине модуля. Тестировал бинарное возведение в степень против 3 различных реализаций расширенного евклида. Результаты такие:
-O2 const modulo:
Binpow time: 0.881338 s
Euclid iterative time: 1.56259 s
Euclid recursive time: 1.00604 s
Euclid oneliner time: 1.48483 s

-O2 nonconst modulo:
Binpow time: 2.81402 s
Euclid iterative time: 1.56268 s
Euclid recursive time: 1.0154 s
Euclid oneliner time: 1.48514 s

no -O2 const modulo:
Binpow time: 1.29055 s
Euclid iterative time: 1.63065 s
Euclid recursive time: 1.3097 s
Euclid oneliner time: 1.49596 s

no -O2 nonconst modulo:
Binpow time: 2.81718 s
Euclid iterative time: 1.63823 s
Euclid recursive time: 1.31089 s
Euclid oneliner time: 1.49404 s

При меньших модулях (до 1000) oneliner работает быстрее остальных реализаций евклида, в остальном относительное положение решений относительно друг друга не меняется при меньших модулях.

2023-05-16 21:44 UTC, wery0 commented on Monomial.h
> +        coefficient_ /= rhs.coefficient_;
Этот assert как раз внутри коэффициента будет. Если конечно коэффициент не какой-то там пользовательский.

2023-05-17 23:58 UTC, wery0 commented on Ideal.h
> +    static_assert(is_polynomial<Polynom>::value);
А чем в данном случае это будет лучше? Мы же только один раз в коде проверяем это условие.

2023-05-22 01:11 UTC, wery0 commented on Monomial.h
> +template<typename CoefficientType, typename VariableOrder = VariableOrders::AsciiOrder, typename DegreeType = int64_t,
Для удобства, ставлю на это ассерты.

2023-05-22 01:18 UTC, wery0 commented on Monomial.h
> +    const std::map<Var, DegreeType>& get_variables() const { return var_store_; }
Сделал прокси объекты, но std::lexicographical_compare начал на них ругаться, так и не разобрался почему((
Поэтому сделал костыль, взяв реализацию std::lexicographical_compare с cppreference.

2023-05-22 01:20 UTC, wery0 commented on Monomial.h
> +    }
Удобно, чтобы gcd и lcm были нормализованы, поэтому инвариант m1 * m2 = gcd(m1, m2) * lcm(m1, m2) выполняется только с точностью до константы. Да и формула lcm = m1 * m2 / gcd будет считаться как минимум вдвое дольше, чем текущая реализация.

2023-05-22 01:23 UTC, wery0 commented on Polynomial.h
> +    Polynomial& operator*=(const auto& rhs) {
А я просто сначала не придумал, как из типа Monom достать его шаблонные параметры.

2023-05-22 01:35 UTC, wery0 commented
Исправил недочёты, добавил бенчмарки, юнит-тесты, нашёл и пофиксил несколько багов и неопределённостей. Кажется, остаётся только протестировать работу библиотеки на каких-то множествах многочленов, которые вы обещали скинуть.

2023-05-22 13:32 UTC, closed without merging